baseURL = "http://chrzaszcz.dev"
languageCode = "en-us"
title = "NerdyGeek"
theme = "hugo-theme-cleanwhite"

paginate = 5
pygmentsUseClassic = true
pygmentsCodeFences = true

publishDir = "docs"

enableEmoji = true

disqusShortname = "lukasz"
[params]
    author = "Łukasz Chrząszcz"
    description = "My memory snapshot"
    keywords = "blog,developer,software engineer"
    sidebar_about_description = "Software Engineer keen on discovering under-the-hood details of everything"
    sidebar_avatar = "images/avatar.png"
    footercontent = "Enter a text here"

    hideCredits = false
    hideCopyright = false

    header_image = "images/home-background-keyboard.jpg"
    SEOTitle = "Nerdy Geek Blog"
    slogan = "Daily portion of beefy nerd knowledge"

    image_404 = "images/404-bg.jpg"
    title_404 = "ChrzaszczException: not-found :("

    featured_tags = false
    featured_condition_size = 1

    # Baidu Analytics
    #  ba_track_id = ""

    # We need a proxy to access Disqus api in China
    # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
    #  disqus_proxy = ""
    disqus_site = ""

    #Enable wechat pay & alipay to allow readers send reward money if they like the articles
    reward = false

    friends = false
    bookmarks = false
    about_me = true



    [params.social]
    rss            = true
    linkedin       = "https://www.linkedin.com/in/%C5%82ukasz-chrz%C4%85szcz-502733b9/"
    github         = "https://github.com/lchrzaszcz"

    [[params.addtional_menus]]
    title =  "ABOUT"
    href =  "/top/about/"
